# Generated by Django 3.2.12 on 2022-02-17 23:17

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('sender_mail', models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, verbose_name='Email Address')),
                ('sender_phone', models.CharField(blank=True, max_length=16, validators=[app.validators.PhoneNumberValidator()], verbose_name='Phone Number')),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
    ]
