# Generated by Django 3.2.12 on 2022-02-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0004_auto_20220219_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('article', 'Article'), ('mobile', 'Mobile'), ('web', 'Web'), ('library', 'Library')], default='web', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('Article', 'Web', 'Mobile', 'Library')}, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='library',
            name='category',
            field=models.CharField(choices=[('article', 'Article'), ('mobile', 'Mobile'), ('web', 'Web'), ('library', 'Library')], default='web', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='category',
            field=models.CharField(choices=[('article', 'Article'), ('mobile', 'Mobile'), ('web', 'Web'), ('library', 'Library')], default='web', max_length=10),
        ),
        migrations.AlterField(
            model_name='web',
            name='category',
            field=models.CharField(choices=[('article', 'Article'), ('mobile', 'Mobile'), ('web', 'Web'), ('library', 'Library')], default='web', max_length=10),
        ),
    ]
