# Generated by Django 3.2.12 on 2022-02-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220219_0215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
