# Generated by Django 3.2.12 on 2022-02-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_image_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='technologies',
            field=models.TextField(default='celery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='technologies',
            field=models.TextField(default='redis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web',
            name='technologies',
            field=models.TextField(default='docker'),
            preserve_default=False,
        ),
    ]
