# Generated by Django 3.2.12 on 2022-02-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220219_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='library',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='web',
            name='category',
        ),
    ]
