# Generated by Django 3.2.12 on 2022-02-23 18:09

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220220_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='language',
        ),
        migrations.RemoveField(
            model_name='application',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='application',
            name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.RemoveField(
            model_name='library',
            name='language',
        ),
        migrations.RemoveField(
            model_name='library',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='library',
            name='title',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
        migrations.CreateModel(
            name='LibraryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('language', models.CharField(max_length=250)),
                ('technologies', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.library')),
            ],
            options={
                'verbose_name': 'Library Translation',
                'db_table': 'app_library_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.article')),
            ],
            options={
                'verbose_name': 'article Translation',
                'db_table': 'app_article_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApplicationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('language', models.CharField(max_length=250)),
                ('technologies', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.application')),
            ],
            options={
                'verbose_name': 'application Translation',
                'db_table': 'app_application_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
